/*
 * Synthetic singer: renders a notation+gamaka score to audio by automating an
 * oscillator's frequency along the exact pitch contour the engine will later
 * measure, then shaping it with three formant bandpasses so it reads as a
 * voice rather than a test tone.
 *
 * This is both the fallback demo voice and the ground truth for the tests: the
 * contour is generated by the same pure code (src/engine/contour.ts) that the
 * unit tests feed directly into the analyser.
 */

import { renderScore, type Score } from '../engine/contour';
import { centsToHz } from '../engine/swara';

/** Formant triples for a sustained open "aa". */
const FORMANTS: { f: number; q: number; gain: number }[] = [
  { f: 700, q: 7, gain: 1.0 },
  { f: 1220, q: 9, gain: 0.5 },
  { f: 2600, q: 11, gain: 0.22 },
];

export interface SynthSingerHandle {
  readonly output: GainNode;
  readonly durationSec: number;
  stop(): void;
  onended?: () => void;
}

/**
 * Schedule a score for playback on `ctx`, starting at `when`.
 * Returns the output node, which the caller routes into the analysis tap.
 */
export function playScore(
  ctx: AudioContext,
  score: Score,
  when = ctx.currentTime + 0.05,
  tonicHz = 220,
): SynthSingerHandle {
  const frames = renderScore(score);
  const output = ctx.createGain();
  output.gain.value = 0.9;

  const osc = ctx.createOscillator();
  osc.type = 'sawtooth';

  // voiced-source amplitude envelope: silent during rests
  const amp = ctx.createGain();
  amp.gain.value = 0;

  const formantBus = ctx.createGain();
  formantBus.gain.value = 0.9;

  for (const fm of FORMANTS) {
    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = fm.f;
    bp.Q.value = fm.q;
    const g = ctx.createGain();
    g.gain.value = fm.gain;
    amp.connect(bp).connect(g).connect(formantBus);
  }
  // a little direct signal keeps the fundamental audible
  const direct = ctx.createGain();
  direct.gain.value = 0.25;
  amp.connect(direct).connect(formantBus);
  formantBus.connect(output);

  osc.connect(amp);

  // --- automate pitch and amplitude along the contour
  let lastHz = tonicHz;
  let voiced = false;
  osc.frequency.setValueAtTime(lastHz, when);
  amp.gain.setValueAtTime(0, when);

  for (const f of frames) {
    const t = when + f.t;
    if (f.cents === null) {
      if (voiced) {
        amp.gain.setTargetAtTime(0, t, 0.015);
        voiced = false;
      }
      continue;
    }
    const hz = centsToHz(f.cents, tonicHz);
    osc.frequency.linearRampToValueAtTime(hz, t);
    lastHz = hz;
    if (!voiced) {
      amp.gain.setTargetAtTime(0.35, t, 0.02);
      voiced = true;
    }
  }

  const durationSec = frames.length ? frames[frames.length - 1].t + 0.1 : 0;
  amp.gain.setTargetAtTime(0, when + durationSec, 0.05);
  osc.start(when);
  osc.stop(when + durationSec + 0.4);

  const handle: SynthSingerHandle = {
    output,
    durationSec,
    stop() {
      try {
        osc.stop();
      } catch {
        /* already stopped */
      }
      output.disconnect();
    },
  };
  osc.onended = () => handle.onended?.();
  return handle;
}
